### ISSUE TITLE
Pamela doesn't run in conda virtual environment

### ISSUE THREAD

**Issue by ArneBachmann** [minrk/pamela#12]
```
(jupyterhub) C:\Users\bach_ar>python -m pamela -a bach_ar
Traceback (most recent call last):
  File "d:\apps\Miniconda3\envs\jupyterhub\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\apps\Miniconda3\envs\jupyterhub\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\apps\Miniconda3\envs\jupyterhub\lib\site-packages\pamela.py", line 49, in <module>
    LIBPAM = CDLL(find_library("pam"))
  File "d:\apps\Miniconda3\envs\jupyterhub\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
```
Could it be that the DLL is somehow hardcoded and not found if pamela installed into the environment?

**Comment by ArneBachmann** [comment]
Yeah, that's what I gathered when I checked available conda builds for pamela, none of which were Windows targets.
I found out how to disable pamela in the project jupyterhub (which is configured to use pamela authentication as the default, but doesn't install that dependency automatically).

**Comment by minrk** [comment]
Indeed! pamela was written for jupyterhub, which *also* doesn't officially support Windows, but it can be used on Windows if you use a custom Authenticator and Spawner.
