### ISSUE TITLE
Freshly installed pamela via conda on windows does not work

### ISSUE THREAD

**Issue by vogt31337** [minrk/pamela#25]
Hi,

just installed pamela and got the following error while execution:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\miniconda3\envs\Test\Lib\site-packages\pamela.py", line 49, in <module>
    LIBPAM = CDLL(find_library("pam"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\Test\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by minrk** [comment]
Correct, pamela does not work on Windows. It's a ctypes wrapper for libpam, which isn't generally (ever?) available on Windows. How are you trying to use PAM on Windows?
